# Generated by Django 5.1.7 on 2025-07-17 23:03

import django.db.models.deletion
import django.utils.timezone
import login.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('dataset_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='dataset_id')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('position', models.CharField(default='', max_length=250, verbose_name='position')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='DiffResult',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='doc_id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=255, verbose_name='filepath')),
                ('network_id', models.CharField(max_length=50, verbose_name='network_id')),
            ],
            options={
                'db_table': 'diff_result',
            },
        ),
        migrations.CreateModel(
            name='DocAndExperiment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('experiment_id', models.CharField(max_length=50, verbose_name='experiment_id')),
                ('doc_id', models.CharField(max_length=50, verbose_name='doc_id')),
            ],
            options={
                'db_table': 'doc_and_experiment',
            },
        ),
        migrations.CreateModel(
            name='ExperimentsTypes',
            fields=[
                ('experiment_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='experiment_id')),
                ('pathname', models.CharField(max_length=100, verbose_name='pathname')),
                ('path_type', models.CharField(max_length=10, verbose_name='path_type')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('parent_id', models.CharField(max_length=50, verbose_name='parent_id')),
                ('dataset_id', models.CharField(max_length=50, verbose_name='dataset_id')),
            ],
            options={
                'db_table': 'experiments_types',
            },
        ),
        migrations.CreateModel(
            name='NetworkAndExperiment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('experiment_id', models.CharField(max_length=50, verbose_name='experiment_id')),
                ('network_id', models.CharField(max_length=50, verbose_name='network_id')),
            ],
            options={
                'db_table': 'network_and_experiment',
            },
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('network_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='network_id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=255, verbose_name='filepath')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('protein_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='protein_id')),
                ('uniprot_accession_id', models.CharField(default='', max_length=50, verbose_name='uniprot_accession_id')),
                ('uniprotkb_id', models.CharField(default='', max_length=64, verbose_name='uniprotkb_id')),
                ('gene_name', models.CharField(default='', max_length=64, verbose_name='gene_name')),
            ],
            options={
                'db_table': 'proteins',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='doc_id')),
                ('filename', models.CharField(default='', max_length=100, verbose_name='filename')),
                ('filepath', models.CharField(default='', max_length=255, verbose_name='filepath')),
                ('doc_type', models.CharField(default='', max_length=5, verbose_name='doc_type')),
                ('label', models.CharField(default='', max_length=5, verbose_name='label')),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'login_customuser',
            },
            managers=[
                ('objects', login.models.CustomUserManager()),
            ],
        ),
    ]
